### ISSUE TITLE
ошибка при запуске

### ISSUE THREAD

**Issue by Elianess** [FSystem88/spymer#15]
```
Traceback (most recent call last):
  File "/usr/bin/spymer", line 5, in <module>
    exec(iDajPfTMpwFqvifvlYqFclNOhsWdfKoUjfDUrvnphYRHMEAOHtAJBSYOyOlGPooX)
  File "<string>", line 677, in <module>
  File "<string>", line 16, in Main
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

обновлял - не помогло
переустановил - не помогло
*заранее спасибо за помощь работягам

**Comment by Elianess** [comment]
> обновлял - не помогло
> переустановил - не помогло
> *заранее спасибо за помощь работягам

`Traceback (most recent call last):
  File "/usr/bin/spymer", line 5, in <module>
    exec(iDajPfTMpwFqvifvlYqFclNOhsWdfKoUjfDUrvnphYRHMEAOHtAJBSYOyOlGPooX)
  File "<string>", line 677, in <module>
  File "<string>", line 16, in Main
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by FSystem88** [comment]
Скинь полностью код ошибки начиная с того что ты ввёл. Либо бан по айпи, либо старая версия

**Comment by TeaPotat** [comment]
Тоже самая проблема

Traceback (most recent call last):                  File "/data/data/com.termux/files/usr/bin/spymer", line 1391, in <module>                             Main()
  File "/data/data/com.termux/files/usr/bin/spymer", line 21, in Main                                   version = requests.post("https://rainbow-t-shirt.com/spymer/version.php").json()["version"]       File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/models.py", line 898, in json                                                return complexjson.loads(self.text, **kwargs)   File "/data/data/com.termux/files/usr/lib/python3.8/json/__init__.py", line 357, in loads             return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                 File "/data/data/com.termux/files/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode         raise JSONDecodeError("Expecting value", s, err.value) from None                                json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)                             $

**Comment by FSystem88** [comment]
Вы не следите за обновлениями программы!!! Будьте внимательны, что написано на гитхабе! Подпишитесь уже на канал, в котором уже давно вышел пост (https://t.me/FS88ch/169) об этой проблеме. Переезжал с одного хостинга на другой. Обновите прога вручную и переустановите!!!

**Comment by vlados9206** [comment]
Такая же проблема не понимаю что делать
Traceback (most recent call last):
  File "/usr/bin/spymer", line 1026, in <module>
    MAIN()
  File "/usr/bin/spymer", line 1017, in MAIN
    Main()
  File "/usr/bin/spymer", line 1016, in Main
    main()
  File "/usr/bin/spymer", line 966, in main
    checkver()
  File "/usr/bin/spymer", line 683, in checkver
    version = requests.post("https://fsystem88.ru/spymer/version.php").json()["version"]
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by vlados9206** [comment]
> Вы не следите за обновлениями программы!!! Будьте внимательны, что написано на гитхабе! Подпишитесь уже на канал, в котором уже давно вышел пост (https://t.me/FS88ch/169) об этой проблеме. Переезжал с одного хостинга на другой. Обновите прога вручную и переустановите!!!

Все равно выскакивает ошибка
