### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by codexprime** [FSystem88/spymer#18]
`Traceback (most recent call last):
  File "spammer.py", line 1058, in <module>
    MAIN()
  File "spammer.py", line 1049, in MAIN
    Main()
  File "spammer.py", line 1048, in Main
    main()
  File "spammer.py", line 992, in main
    checkver()
  File "spammer.py", line 681, in checkver
    version = requests.post("https://fsystem88.ru/spymer/version.php").json()["version"]
  File "/usr/lib/python3/dist-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "spammer.py", line 1058, in <module>
    MAIN()
  File "spammer.py", line 1049, in MAIN
    Main()
  File "spammer.py", line 1048, in Main
    main()
  File "spammer.py", line 992, in main
    checkver()
  File "spammer.py", line 681, in checkver
    version = requests.post("https://fsystem88.ru/spymer/version.php").json()["version"]
  File "/usr/lib/python3/dist-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

привет, подскажи пожалуйста как пофиксить?

**Comment by FSystem88** [comment]
Напишите мне в телеграмм. t.me/FSystem88
