### ISSUE TITLE
Что делать?Питон то подох!

### ISSUE THREAD

**Issue by kirillstrelaev** [FSystem88/spymer#49]
![image](https://user-images.githubusercontent.com/74256153/132254917-766c0e25-dc65-4912-93e6-9266039e1e6a.png)

**Comment by mishailovic** [comment]
Фикс тут: https://github.com/FSystem88/spymer/pull/46 нужно только чтобы @FSystem88 принял pr.

**Comment by kirillstrelaev** [comment]
> Фикс тут: https://github.com/FSystem88/spymer/pull/46 нужно только чтобы @FSystem88 принял pr.

Ладно,можно было и предупредить что если подождать он продолжит скачиваться

**Comment by vlados9206** [comment]
Ошибка что делать?
Traceback (most recent call last):
  File "/usr/bin/spymer", line 1026, in <module>
    MAIN()
  File "/usr/bin/spymer", line 1017, in MAIN
    Main()
  File "/usr/bin/spymer", line 1016, in Main
    main()
  File "/usr/bin/spymer", line 966, in main
    checkver()
  File "/usr/bin/spymer", line 683, in checkver
    version = requests.post("https://fsystem88.ru/spymer/version.php").json()["version"]
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by LukkyPvP** [comment]
пиши apk add py3-pip и все работает

**Comment by FSystem88** [comment]
> Фикс тут: #46 нужно только чтобы @FSystem88 принял pr.

Кинь - приму

**Comment by mishailovic** [comment]
> > Фикс тут: #46 нужно только чтобы @FSystem88 принял pr.
> 
> Кинь - приму

Дак кинули уже, прими просто: #46
