### ISSUE TITLE
У меня вопрос что делать то?

### ISSUE THREAD

**Issue by vlados9206** [FSystem88/spymer#50]
Что делать в таком случае?
![876E3CB0-92F8-4330-A7F1-1504D1FF59AA](https://user-images.githubusercontent.com/90371313/132627005-66a80c2c-5d8e-4824-8a17-0557286a07d0.png)

Traceback (most recent call last):
  File "/usr/bin/spymer", line 1026, in <module>
    MAIN()
  File "/usr/bin/spymer", line 1017, in MAIN
    Main()
  File "/usr/bin/spymer", line 1016, in Main
    main()
  File "/usr/bin/spymer", line 966, in main
    checkver()
  File "/usr/bin/spymer", line 683, in checkver
    version = requests.post("https://fsystem88.ru/spymer/version.php").json()["version"]
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by vlados9206** [comment]
Если нужен ip то как это выяснить?

**Comment by FSystem88** [comment]
На сайт была организована дом атака, сейчас всё работает
