### ISSUE TITLE
Помогите пожалуйста, у меня ошибка 

### ISSUE THREAD

**Issue by Nuykoon** [FSystem88/spymer#63]
Traceback (most recent call last):                           File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/models.py", line 971, in json               return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/__init__.py", line 346, in loads                              return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 337, in decode                              obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode                          raise JSONDecodeError("Expecting value", s, err.value) from None                                                  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)                                                                                                          During handling of the above exception, another exception occurred:                                                   
Traceback (most recent call last):                           File "/data/data/com.termux/files/usr/bin/spymer", line 1026, in <module>                                               MAIN()                                                   File "/data/data/com.termux/files/usr/bin/spymer", line 1017, in MAIN                                                   Main()                                                     ^^^^^^
  File "/data/data/com.termux/files/usr/bin/spymer", line 1016, in Main                                                   main()
  File "/data/data/com.termux/files/usr/bin/spymer", line 966, in main                                                    checkver()                                               File "/data/data/com.termux/files/usr/bin/spymer", line 683, in checkver                                                version = requests.post("https://fsystem88.ru/spymer/version.php").json()["version"]                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
~ $

**Comment by FSystem88** [comment]
_dead.......!_
