### ISSUE TITLE
Ошибка запуска

### ISSUE THREAD

**Issue by IronRUS** [FSystem88/spymer#8]
Traceback (most recent call last):
  File "spammer.py", line 1391, in <module>
    Main()
  File "spammer.py", line 21, in Main
    version = requests.post("https://rainbow-t-shirt.com/spymer/version.php").json()["version"]
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Как это решить или это баг?

**Comment by Marryson845** [comment]
Там че то сервера легли, админ в тг сам говорил

ср, 29 апр. 2020 г., 2:35 IronRUS <notifications@github.com>:
