### ISSUE TITLE
Нужна помощь

### ISSUE THREAD

**Issue by Just-guy-root** [FSystem88/spymer#9]
Traceback (most recent call last):
  File "spammer.py", line 1391, in <module>
    Main()
  File "spammer.py", line 21, in Main
    version = requests.post("https://rainbow-t-shirt.com/spymer/version.php").json()["version"]
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mishailovic** [comment]
Проблема уже решена, попробуй чистую установку, если ты ещё юзаешь exe, то он пока не работает

**Comment by Marryson845** [comment]
Спасибо за оповещение, я на Termux`е гоняюОтправлено с моего телефона Huawei-------- Исходное сообщение --------От: Mikhail Kuznetsov <notifications@github.com>Дата: пн, 4 мая 2020 г., 14:35Кому: FSystem88/spymer <spymer@noreply.github.com>Копия: Subscribed <subscribed@noreply.github.com>Тема: Re: [FSystem88/spymer] Нужна помощь (#9)

Проблема уже решена, попробуй чистую установку, если ты ещё юзаешь exe, то он пока не работает
